# Generated by Django 6.0 on 2026-01-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileCleanupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delete_uploaded_files",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, uploaded files will be deleted after each RECLAIM run.",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Cleanup Settings",
                "verbose_name_plural": "File Cleanup Settings",
            },
        ),
        migrations.CreateModel(
            name="Reservoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
